spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hai_music?useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yangyihi2001
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # 配置redis
  redis:
    host: 127.0.0.1 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    database: 0   #Redis数据库索引（默认为0）
    timeout: 10000  #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 5  #连接池中的最大空闲连接
        min-idle: 0  #连接池中的最小空闲连接
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
  elasticsearch:
    uris: http://81.68.127.141:9200
    username: elastic
    password: yangyihi2001


#配置mybatis
mybatis-plus:
  #启动bean实体类简化写法
  type-aliases-package: com.yanghi.haimusic.bean
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
  #注意有了configuration配置，就不能配置config-location了
  configuration: #指定mybatis的全局配置
    # 配置驼峰命名 自动注入
    map-underscore-to-camel-case: true
  global-config:
    banner: false

# 配置actuator的webapi暴露
management:
  endpoints:
    #默认开启所有监控端点
    enabled-by-default: false  #关闭所有监控端点
    web:
      exposure:
        include: '*' # 以web方式暴露所有监控端点

  #对某个监控端点的具体配置
  endpoint:
    health:
      show-details: always # 显示监控的详细信息
      enabled: true # 单独开启健康端点
    info:
      enabled: true # 单独开启info端点
    metrics:
      enabled: true # 单独开启指标端点

server:
  port: 8081






